# -*- coding: utf-8 -*-
"""主治医意見書 フォーム定義（正典）.

このファイルが唯一の「項目マスタ」です。ここから
  - schema/ikensho.schema.json   … 論理項目定義（Python版 / ブラウザ版で共有）
  - templates/official_v1.json   … 公式様式の物理座標テンプレート
を生成します。

チェックボックスの物理座標は master/主医師意見書.pdf のテキストレイヤから
自動抽出するため、ここでは「文書順に並んだ選択肢の列」だけを定義します。
"""

# ---------------------------------------------------------------------------
# 型
#   text      : 1行テキスト
#   textarea  : 複数行テキスト
#   choice    : チェックボックス単一選択
#   multi     : チェックボックス複数選択
#   flag      : 単独チェックボックス（該当/非該当）
#   circle    : 印刷された選択肢を丸で囲む方式（男・女 / 明・大・昭 など）
# ---------------------------------------------------------------------------

SECTIONS = [
    # =====================================================================
    ("header", "基本情報", [
        dict(id="entry_date", label="記入日", type="text", page=1,
             rect=[452, 44, 566, 60], hint="令和○年○月○日"),
        dict(id="applicant_furigana", label="申請者ふりがな", type="text", page=1,
             rect=[168, 67, 336, 82]),
        dict(id="applicant_name", label="申請者氏名", type="text", page=1,
             rect=[108, 83, 336, 107]),
        dict(id="applicant_sex", label="性別", type="circle", page=1,
             rect=[332, 74, 354, 117], options=["男", "女"]),
        dict(id="birth_era", label="生年（元号）", type="circle", page=1,
             rect=[106, 108, 159, 123], options=["明", "大", "昭"]),
        dict(id="birth_date", label="生年月日", type="text", page=1,
             rect=[159, 108, 258, 123], hint="○年○月○日"),
        dict(id="age", label="年齢", type="text", page=1,
             rect=[281, 108, 312, 123]),
        dict(id="postal_code", label="郵便番号", type="text", page=1,
             rect=[371, 67, 470, 82]),
        dict(id="applicant_address", label="住所", type="text", page=1,
             rect=[358, 82, 566, 106]),
        dict(id="applicant_phone", label="連絡先", type="text", page=1,
             rect=[406, 107, 566, 123]),
        dict(id="consent", label="意見書利用への同意", type="choice", page=1,
             options=["同意する", "同意しない"]),
        dict(id="doctor_name", label="医師氏名", type="text", page=1,
             rect=[82, 151, 352, 166]),
        dict(id="clinic_name", label="医療機関名", type="text", page=1,
             rect=[92, 164, 352, 179]),
        dict(id="clinic_address", label="医療機関所在地", type="text", page=1,
             rect=[112, 177, 352, 192]),
        dict(id="clinic_phone", label="電話", type="text", page=1,
             rect=[377, 164, 566, 179]),
        dict(id="clinic_fax", label="FAX", type="text", page=1,
             rect=[372, 177, 566, 192]),
        dict(id="last_exam_date", label="(1) 最終診察日", type="text", page=1,
             rect=[176, 198, 562, 214], hint="令和○年○月○日"),
        dict(id="report_count", label="(2) 意見書作成回数", type="choice", page=1,
             options=["初回", "2回目以上"]),
        dict(id="other_dept_visit", label="(3) 他科受診の有無", type="choice", page=1,
             options=["有", "無"]),
        dict(id="other_dept", label="(3) 他科受診（診療科）", type="multi", page=1,
             options=["内科", "精神科", "外科", "整形外科", "脳神経外科", "皮膚科",
                      "泌尿器科", "婦人科", "眼科", "耳鼻咽喉科",
                      "リハビリテーション科", "歯科", "その他"]),
        dict(id="other_dept_other_text", label="(3) 他科受診 その他", type="text", page=1,
             rect=[470, 255, 562, 270]),
    ]),
    # =====================================================================
    ("s1", "１．傷病に関する意見", [
        dict(id="diagnosis1_name", label="(1) 診断名1", type="text", page=1,
             rect=[74, 313, 272, 330]),
        dict(id="diagnosis1_era", label="(1) 診断名1 発症元号", type="circle", page=1,
             rect=[331, 313, 417, 330], options=["昭和", "平成", "令和"]),
        dict(id="diagnosis1_date", label="(1) 診断名1 発症年月日", type="text", page=1,
             rect=[417, 313, 562, 330], hint="○年○月○日頃"),
        dict(id="diagnosis2_name", label="(1) 診断名2", type="text", page=1,
             rect=[74, 333, 272, 350]),
        dict(id="diagnosis2_era", label="(1) 診断名2 発症元号", type="circle", page=1,
             rect=[331, 333, 417, 350], options=["昭和", "平成", "令和"]),
        dict(id="diagnosis2_date", label="(1) 診断名2 発症年月日", type="text", page=1,
             rect=[417, 333, 562, 350], hint="○年○月○日頃"),
        dict(id="diagnosis3_name", label="(1) 診断名3", type="text", page=1,
             rect=[74, 353, 272, 370]),
        dict(id="diagnosis3_era", label="(1) 診断名3 発症元号", type="circle", page=1,
             rect=[331, 353, 417, 370], options=["昭和", "平成", "令和"]),
        dict(id="diagnosis3_date", label="(1) 診断名3 発症年月日", type="text", page=1,
             rect=[417, 353, 562, 370], hint="○年○月○日頃"),
        dict(id="symptom_stability", label="(2) 症状としての安定性", type="choice", page=1,
             options=["安定", "不安定", "不明"]),
        dict(id="stability_detail", label="(2) 不安定の場合の具体的な状況", type="text", page=1,
             rect=[216, 386, 562, 402]),
        dict(id="treatment_course", label="(3) 経過及び治療内容", type="textarea", page=1,
             rect=[41, 437, 561, 553]),
    ]),
    # =====================================================================
    ("s2", "２．特別な医療（過去14日間以内）", [
        dict(id="special_med_procedure", label="処置内容", type="multi", page=1,
             options=["点滴の管理", "中心静脈栄養", "透析", "ストーマの処置", "酸素療法",
                      "レスピレーター", "気管切開の処置", "疼痛の看護", "経管栄養"]),
        dict(id="special_med_response", label="特別な対応", type="multi", page=1,
             options=["モニター測定", "褥瘡の処置"]),
        dict(id="special_med_incontinence", label="失禁への対応", type="multi", page=1,
             options=["カテーテル"]),
    ]),
    # =====================================================================
    ("s3", "３．心身の状態に関する意見", [
        dict(id="adl_disabled", label="(1) 障害高齢者の日常生活自立度", type="choice", page=1,
             options=["自立", "J1", "J2", "A1", "A2", "B1", "B2", "C1", "C2"]),
        dict(id="adl_dementia", label="(1) 認知症高齢者の日常生活自立度", type="choice", page=1,
             options=["自立", "Ⅰ", "Ⅱa", "Ⅱb", "Ⅲa", "Ⅲb", "Ⅳ", "Ｍ"]),
        dict(id="short_term_memory", label="(2) 短期記憶", type="choice", page=1,
             options=["問題なし", "問題あり"]),
        dict(id="decision_ability", label="(2) 日常の意思決定を行うための認知能力", type="choice", page=1,
             options=["自立", "いくらか困難", "見守りが必要", "判断できない"]),
        dict(id="communication_ability", label="(2) 自分の意思の伝達能力", type="choice", page=1,
             options=["伝えられる", "いくらか困難", "具体的要求に限られる", "伝えられない"]),
        dict(id="bpsd_presence", label="(3) 認知症の行動・心理症状(BPSD)の有無", type="choice", page=1,
             options=["無", "有"]),
        dict(id="bpsd_items", label="(3) BPSD 症状", type="multi", page=1,
             options=["幻視・幻聴", "妄想", "昼夜逆転", "暴言", "暴行", "介護への抵抗",
                      "徘徊", "火の不始末", "不潔行為", "異食行動", "性的問題行動", "その他"]),
        dict(id="bpsd_other_text", label="(3) BPSD その他", type="text", page=1,
             rect=[446, 766, 552, 782]),
        dict(id="other_psych_presence", label="(4) その他の精神・神経症状", type="choice", page=2,
             options=["無", "有"]),
        dict(id="other_psych_symptom_name", label="(4) 症状名", type="text", page=2,
             rect=[161, 49, 341, 64]),
        dict(id="specialist_consult", label="(4) 専門医受診の有無", type="choice", page=2,
             options=["有", "無"]),
        dict(id="specialist_consult_detail", label="(4) 専門医受診 内容", type="text", page=2,
             rect=[444, 49, 518, 64]),
        dict(id="dominant_hand", label="(5) 利き腕", type="choice", page=2,
             options=["右", "左"]),
        dict(id="height_cm", label="(5) 身長(cm)", type="text", page=2,
             rect=[185, 74, 234, 90]),
        dict(id="weight_kg", label="(5) 体重(kg)", type="text", page=2,
             rect=[262, 74, 299, 90]),
        dict(id="weight_change", label="(5) 過去6ヶ月の体重の変化", type="choice", page=2,
             options=["増加", "維持", "減少"]),
        dict(id="limb_defect", label="(5) 四肢欠損", type="flag", page=2, match="四肢欠損"),
        dict(id="limb_defect_site", label="(5) 四肢欠損 部位", type="text", page=2,
             rect=[191, 88, 432, 103]),
        dict(id="paralysis", label="(5) 麻痺", type="flag", page=2, match="麻痺"),
        dict(id="paralysis_right_upper", label="(5) 麻痺 右上肢", type="flag", page=2, match="右上肢"),
        dict(id="paralysis_right_upper_degree", label="(5) 麻痺 右上肢 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="paralysis_left_upper", label="(5) 麻痺 左上肢", type="flag", page=2, match="左上肢"),
        dict(id="paralysis_left_upper_degree", label="(5) 麻痺 左上肢 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="paralysis_right_lower", label="(5) 麻痺 右下肢", type="flag", page=2, match="右下肢"),
        dict(id="paralysis_right_lower_degree", label="(5) 麻痺 右下肢 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="paralysis_left_lower", label="(5) 麻痺 左下肢", type="flag", page=2, match="左下肢"),
        dict(id="paralysis_left_lower_degree", label="(5) 麻痺 左下肢 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="paralysis_other", label="(5) 麻痺 その他", type="flag", page=2, match="その他"),
        dict(id="paralysis_other_site", label="(5) 麻痺 その他 部位", type="text", page=2,
             rect=[236, 133, 284, 148]),
        dict(id="paralysis_other_degree", label="(5) 麻痺 その他 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="muscle_weakness", label="(5) 筋力の低下", type="flag", page=2, match="筋力の低下"),
        dict(id="muscle_weakness_site", label="(5) 筋力の低下 部位", type="text", page=2,
             rect=[191, 148, 369, 163]),
        dict(id="muscle_weakness_degree", label="(5) 筋力の低下 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="joint_contracture", label="(5) 関節の拘縮", type="flag", page=2, match="関節の拘縮"),
        dict(id="joint_contracture_site", label="(5) 関節の拘縮 部位", type="text", page=2,
             rect=[192, 163, 369, 178]),
        dict(id="joint_contracture_degree", label="(5) 関節の拘縮 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="joint_pain", label="(5) 関節の痛み", type="flag", page=2, match="関節の痛み"),
        dict(id="joint_pain_site", label="(5) 関節の痛み 部位", type="text", page=2,
             rect=[191, 178, 369, 193]),
        dict(id="joint_pain_degree", label="(5) 関節の痛み 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="ataxia", label="(5) 失調・不随意運動", type="flag", page=2, match="失調・不随意運動"),
        dict(id="ataxia_upper", label="(5) 失調・不随意運動 上肢", type="multi", page=2,
             options=["右", "左"]),
        dict(id="ataxia_lower", label="(5) 失調・不随意運動 下肢", type="multi", page=2,
             options=["右", "左"]),
        dict(id="ataxia_trunk", label="(5) 失調・不随意運動 体幹", type="multi", page=2,
             options=["右", "左"]),
        dict(id="pressure_ulcer", label="(5) 褥瘡", type="flag", page=2, match="褥瘡"),
        dict(id="pressure_ulcer_site", label="(5) 褥瘡 部位", type="text", page=2,
             rect=[192, 208, 369, 223]),
        dict(id="pressure_ulcer_degree", label="(5) 褥瘡 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
        dict(id="other_skin_disease", label="(5) その他の皮膚疾患", type="flag", page=2, match="その他の皮膚疾患"),
        dict(id="other_skin_disease_site", label="(5) その他の皮膚疾患 部位", type="text", page=2,
             rect=[191, 223, 369, 238]),
        dict(id="other_skin_disease_degree", label="(5) その他の皮膚疾患 程度", type="choice", page=2,
             options=["軽", "中", "重"]),
    ]),
    # =====================================================================
    ("s4", "４．生活機能とサービスに関する意見", [
        dict(id="outdoor_walking", label="(1) 屋外歩行", type="choice", page=2,
             options=["自立", "介助があればしている", "していない"]),
        dict(id="wheelchair", label="(1) 車いすの使用", type="choice", page=2,
             options=["用いていない", "主に自分で操作している", "主に他人が操作している"]),
        dict(id="walking_aid", label="(1) 歩行補助具・装具の使用", type="multi", page=2,
             options=["用いていない", "屋外で使用", "屋内で使用"]),
        dict(id="eating", label="(2) 食事行為", type="choice", page=2,
             options=["自立ないし何とか自分で食べられる", "全面介助"]),
        dict(id="nutrition_status", label="(2) 現在の栄養状態", type="choice", page=2,
             options=["良好", "不良"]),
        dict(id="nutrition_note", label="(2) 栄養・食生活上の留意点", type="text", page=2,
             rect=[183, 353, 470, 368]),
        dict(id="risk_conditions", label="(3) 発生の可能性の高い状態", type="multi", page=2,
             options=["尿失禁", "転倒・骨折", "移動能力の低下", "褥瘡", "心肺機能の低下",
                      "閉じこもり", "意欲低下", "徘徊", "低栄養", "摂食・嚥下機能低下",
                      "脱水", "易感染性", "がん等による疼痛", "その他"]),
        dict(id="risk_other_text", label="(3) その他の状態", type="text", page=2,
             rect=[455, 392, 556, 407]),
        dict(id="risk_policy", label="(3) 対処方針", type="text", page=2,
             rect=[110, 406, 558, 422]),
        dict(id="service_outlook", label="(4) 生活機能の維持・改善の見通し", type="choice", page=2,
             options=["期待できる", "期待できない", "不明"]),
        dict(id="medical_management", label="(5) 医学的管理の必要性", type="multi", page=2,
             options=["訪問診療", "訪問看護", "訪問歯科診療", "訪問薬剤管理指導",
                      "訪問リハビリテーション", "短期入所療養介護", "訪問歯科衛生指導",
                      "訪問栄養食事指導", "通所リハビリテーション", "老人保健施設",
                      "介護医療院", "その他の医療系サービス", "特記すべき項目なし"]),
        dict(id="medical_management_other_text", label="(5) その他の医療系サービス 内容",
             type="text", page=2, rect=[475, 505, 556, 520]),
        dict(id="service_caution", label="(6) サービス提供時の留意事項", type="multi", page=2,
             options=["血圧", "摂食", "嚥下", "移動", "運動", "その他", "特記すべき項目なし"]),
        dict(id="caution_bp_text", label="(6) 血圧 内容", type="text", page=2,
             rect=[76, 545, 206, 560]),
        dict(id="caution_eating_text", label="(6) 摂食 内容", type="text", page=2,
             rect=[246, 545, 366, 560]),
        dict(id="caution_swallow_text", label="(6) 嚥下 内容", type="text", page=2,
             rect=[406, 545, 556, 560]),
        dict(id="caution_move_text", label="(6) 移動 内容", type="text", page=2,
             rect=[76, 558, 206, 573]),
        dict(id="caution_exercise_text", label="(6) 運動 内容", type="text", page=2,
             rect=[246, 558, 366, 573]),
        dict(id="caution_other_text", label="(6) その他 内容", type="text", page=2,
             rect=[416, 558, 556, 573]),
        dict(id="infection", label="(7) 感染症の有無", type="choice", page=2,
             options=["無", "有", "不明"]),
        dict(id="infection_detail", label="(7) 感染症 内容", type="text", page=2,
             rect=[155, 598, 440, 613]),
    ]),
    # =====================================================================
    ("s5", "５．特記すべき事項", [
        dict(id="special_notes", label="特記すべき事項", type="textarea", page=2,
             rect=[41, 682, 561, 785]),
    ]),
]

# ---------------------------------------------------------------------------
# マスターPDF上の □ を文書順に並べたときの (field_id, option_index) 列。
# tools/build_master_template.py がこの順序でチェックボックス座標を割り当てます。
# flag 型は option_index=0 の 1 個だけを持ちます。
# ---------------------------------------------------------------------------

def _seq(*pairs):
    out = []
    for field_id, n in pairs:
        for i in range(n):
            out.append((field_id, i))
    return out


BOX_ORDER = {
    1: _seq(
        ("consent", 2),
        ("report_count", 2),
        ("other_dept_visit", 2),
        ("other_dept", 13),
        ("symptom_stability", 3),
        ("special_med_procedure", 9),
        ("special_med_response", 2),
        ("special_med_incontinence", 1),
        ("adl_disabled", 9),
        ("adl_dementia", 8),
        ("short_term_memory", 2),
        ("decision_ability", 4),
        ("communication_ability", 4),
        ("bpsd_presence", 2),
        ("bpsd_items", 12),
    ),
    2: _seq(
        ("other_psych_presence", 2),
        ("specialist_consult", 2),
        ("dominant_hand", 2),
        ("weight_change", 3),
        ("limb_defect", 1),
        ("paralysis", 1),
        ("paralysis_right_upper", 1),
        ("paralysis_right_upper_degree", 3),
        ("paralysis_left_upper", 1),
        ("paralysis_left_upper_degree", 3),
        ("paralysis_right_lower", 1),
        ("paralysis_right_lower_degree", 3),
        ("paralysis_left_lower", 1),
        ("paralysis_left_lower_degree", 3),
        ("paralysis_other", 1),
        ("paralysis_other_degree", 3),
        ("muscle_weakness", 1),
        ("muscle_weakness_degree", 3),
        ("joint_contracture", 1),
        ("joint_contracture_degree", 3),
        ("joint_pain", 1),
        ("joint_pain_degree", 3),
        ("ataxia", 1),
        ("ataxia_upper", 2),
        ("ataxia_lower", 2),
        ("ataxia_trunk", 2),
        ("pressure_ulcer", 1),
        ("pressure_ulcer_degree", 3),
        ("other_skin_disease", 1),
        ("other_skin_disease_degree", 3),
        ("outdoor_walking", 3),
        ("wheelchair", 3),
        ("walking_aid", 3),
        ("eating", 2),
        ("nutrition_status", 2),
        ("risk_conditions", 14),
        ("service_outlook", 3),
        ("medical_management", 13),
        ("service_caution", 7),
        ("infection", 3),
    ),
}


def all_fields():
    for sec_id, sec_title, fields in SECTIONS:
        for f in fields:
            yield sec_id, sec_title, f


def field_map():
    return {f["id"]: f for _, _, f in all_fields()}
